import { GetStaticProps } from 'next'
import Head from 'next/head'
import prisma from '../../lib/prisma'

import type { Post } from '@prisma/client'

export const getStaticProps: GetStaticProps = async () => {
  const post = await prisma.post.findMany()

  return {
    props: { post }
  }
}

type Props = {
  post: Post[]
}

export default function Home(props: Props) {
  console.log(props.post)

  return (
    <>
      <Head>
        <title>Pages Local Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Pages</p>
      </main>
    </>
  )
}
